services:
  - type: web
    name: mojeskola-bukovany
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
